config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmations => "users/confirmations",
      :passwords => "users/passwords"}
  root 'questionable_pizzas#index'
  get 'questionable_pizzas/ask_cam'
  post 'questionable_pizzas/create' => 'questionable_pizzas#create'
  get 'questionable_pizzas/create' => 'questionable_pizzas#ask_cam'
  get 'questionable_pizzas/cam_says/:id/:is_it_pizza' => 'questionable_pizzas#cam_says'
  get 'questionable_pizzas' => 'questionable_pizzas#index'
  get 'gayyyyyyyyyy' => 'questionable_pizzas#index'
end

app/models/questionable_pizza.rb
class QuestionablePizza < ActiveRecord::Base
  YOUTUBE_REGEX = %r(^(http[s]*:\/\/)?(www.)?(youtube.com|youtu.be)\/(watch\?v=){0,1}([a-zA-Z0-9_-]{11}))

  paginates_per 15

  belongs_to :user, optional: true
  has_attached_file :pizza_image, default_url: "/pizza_images/missing.png"
  validates_attachment_content_type :pizza_image, content_type: /\Aimage\/.*\Z/, :if => Proc.new { |qp| qp.pizza_image.file? }, :size => { less_than: 10.megabytes }
  has_attached_file :pizza_video, default_url: "/pizza_videos/missing.png"
  validates_attachment_content_type :pizza_video, content_type: /\Avideo\/.*\Z/, :if => Proc.new { |qp| qp.pizza_video.file? }, :size => { less_than: 40.megabytes }
  before_validation :set_is_it_pizza
  validate :presence_of_video_or_image
  validate :ip_waiting_on_cam, :on => :create
  validates :client_ip, :presence => true

  attr_accessor :pizza_image_link
  attr_accessor :pizza_video_link

  MAX_NUMBER_OF_PENDING_PIZZAS = 5

  enum is_it_pizza: [ :yes, :no, :waiting_on_cam ]

  after_create :ask_cam

  after_update do
    if !self.user.nil? && self.is_it_pizza_was == "waiting_on_cam"  && self.is_it_pizza != "waiting_on_cam"
      AskCamMailer.notify_user_of_pizza(self.user, self).deliver
    end
  end

  def pizza_media
    if self.is_pizza_image
      return pizza_image
    end
    self.pizza_video
  end

  def is_pizza_image
    self.pizza_image.file?
  end

  def self.create_with_video_url(params, video_url)
    questionable_pizza = QuestionablePizza.new(params)
    begin
      questionable_pizza.pizza_video = download_video(video_url)
      questionable_pizza.save
    rescue Errno::ENOENT
      questionable_pizza.errors.add(:pizza_video_link, "can not retrieve video")
      questionable_pizza
    end
    questionable_pizza
  end

  def self.create_with_image_url(params, image_url)
    questionable_pizza = QuestionablePizza.new(params)
    begin
      questionable_pizza.pizza_image = open(image_url)
      questionable_pizza.save
    rescue Errno::ENOENT
      questionable_pizza.errors.add(:pizza_iamge_link, "can not retrieve image")
      questionable_pizza
    end
    questionable_pizza
  end

  private

  def self.download_video(video_url)
    if YOUTUBE_REGEX.match(video_url)
      temp_file = Tempfile.new(['youtube_pizza'])
      temp_file_path = temp_file.path + '.mp4'
      YoutubeDL.download(video_url, :output => temp_file_path, :format => 'mp4')
      open(temp_file_path)
    else
      open(video_url)
    end
  end

  def set_is_it_pizza
    self.is_it_pizza ||= "waiting_on_cam"
  end

  def ask_cam
    AskCamMailer.ask_cam(self.pizza_media.url, self.id, self.is_pizza_image).deliver
  end

  def ip_waiting_on_cam
    if !user.nil?
      user.can_ask_cam
    else
      self.errors.add(:base, "woah woah woah slow down") if self.is_it_pizza == "waiting_on_cam" && QuestionablePizza.where(:client_ip => self.client_ip, :is_it_pizza => QuestionablePizza.is_it_pizzas[:waiting_on_cam]).count > 0
    end
  end

  def presence_of_video_or_image
    self.errors.add(:pizza_media, "must have only video or pizza") if self.pizza_image.file? && self.pizza_video.file?
    self.errors.add(:pizza_media, "must have either video or pizza") if !self.pizza_image.file? && !self.pizza_video.file?
  end
end

app/controllers/questionable_pizzas_controller.rb
class QuestionablePizzasController < ApplicationController
  before_action :authenticate_cam, only: :cam_says

  def ask_cam
    can_ask?
    @is_it_pizza = QuestionablePizza.new
  end

  def create
    redirect_to questionable_pizzas_ask_cam_path, :flash => { :error => "No, I don't think so..." } and return unless can_ask?
    @show_index_link = params[:show_index_link] != "false"
    create_params = questionable_pizza_params
    create_params[:is_it_pizza] = :yes if @current_user&.is_cam?
    pizza_image_link = create_params.delete(:pizza_image_link)
    pizza_video_link = create_params.delete(:pizza_video_link)

    if !pizza_image_link.nil? && pizza_image_link.length > 0
      @is_it_pizza = QuestionablePizza.create_with_image_url(create_params, pizza_image_link)
    elsif !pizza_video_link.nil? && pizza_video_link.length > 0
      @is_it_pizza = QuestionablePizza.create_with_video_url(create_params, pizza_video_link)
    else
      @is_it_pizza = QuestionablePizza.create(create_params)
    end
    flash[:error]

    respond_to do |format|
      format.html {
        if @is_it_pizza.errors.any?
          flash[:error] = @is_it_pizza.errors.full_messages.join(". ")
          redirect_to questionable_pizzas_ask_cam_path, :flash => { :error =>  @is_it_pizza.errors.full_messages.join(". ") }
        end
      }
      format.json {
        if @is_it_pizza.errors.any?
          render json: @is_it_pizza.errors.full_messages, :status => :unprocessable_entity
        else
          head :ok
        end
      }
    end
  end


  def cam_says
    @questionable_pizza = QuestionablePizza.find(params[:id])
    @saved_pizza = false

    if @questionable_pizza
      @questionable_pizza.is_it_pizza = params[:is_it_pizza]
      @saved_pizza = @questionable_pizza.save
    end
  end

  def index
    @questionable_pizzas = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:yes]).order('updated_at DESC')
    @questionable_pizzas = @questionable_pizzas.page(params[:page])
  end

  private

  def can_ask?
    if !@current_user.nil?
      @can_ask_cam = @current_user.can_ask_cam
      @is_temporary_banned = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:no], :user => @current_user).where("created_at > ? ", DateTime.now - 69.hours).count > 2

      if @is_temporary_banned
        @unban_time = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:no], :user => @current_user).where("created_at > ? ", DateTime.now - 69.hours).order("created_at ASC").first.created_at + 69.hours
      end
    else
      @can_ask_cam = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:waiting_on_cam], :client_ip => request.remote_ip).count == 0
      @is_temporary_banned = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:no], :client_ip => request.remote_ip).where("created_at > ? ", DateTime.now - 69.hours).count > 2

      if @is_temporary_banned
        @unban_time = QuestionablePizza.where(:is_it_pizza => QuestionablePizza.is_it_pizzas[:no], :client_ip => request.remote_ip).where("created_at > ? ", DateTime.now - 69.hours).order("created_at ASC").first.created_at + 69.hours
      end
    end
    @can_ask_cam
  end

  def questionable_pizza_params
    accepted_params = params.fetch(:questionable_pizza, {}).permit(:pizza_image, :pizza_video, :pizza_image_link, :pizza_video_link)
    accepted_params[:client_ip] = request.remote_ip
    accepted_params[:user] = @current_user
    accepted_params
  end

  def authenticate_cam
    unless @current_user&.is_cam?
      http_basic_authenticate_or_request_with(name: "cam", password: Rails.application.config.cam_password)
    end
  end
end

app/helpers/questionable_pizzas_helper.rb
module QuestionablePizzasHelper
end

app/views/questionable_pizzas/_questionable_pizza.html.erb
<ul>
  <% if questionable_pizza.pizza_image.exists? %>
    <%= image_tag questionable_pizza.pizza_image.url, :width => '300' %>
  <% else %>
    <%= video_tag questionable_pizza.pizza_video.url, :width => '300', :controls => true %>
  <% end %>
</ul>

app/views/questionable_pizzas/ask_cam.html.erb
<% if @is_temporary_banned %>
    <h1>Looks like your pizzas are shit. You've been banned until <%= @unban_time %></h1>
<% elsif @can_ask_cam %>
    <h1>Is it Pizza? Ask Cam</h1>
    <%= form_for @is_it_pizza, url: questionable_pizzas_create_path, html: { multipart: true } do |form| %>
        <label>Pizza Image</label>
        <%= form.file_field :pizza_image, as: :file %>
        <label>Pizza Video</label>
        <%= form.file_field :pizza_video, as: :file %>
        <%= form.submit 'Ask Cam' %>
        <br>
        <h1>ORRRRR, put in a nice link</h1>
        <label>Pizza Image Link</label>
        <%= form.text_field :pizza_image_link %>
        <label>Pizza Video Link (...do you guys like youtube videos?)</label>
        <%= form.text_field :pizza_video_link %>
        <%= form.submit 'Ask Cam' %>
        <p id="error"><%= flash[:error] %></p>
    <% end %>
<% else %>
    <h1>Woah slow down!!!! You gotta give cam some time to decide if your last one was pizza.</h1>
<% end %>

app/views/questionable_pizzas/cam_says.html.erb
<% if @saved_pizza %>
    <h1>WOWIE CAM! I'm glad you're here. That was a tricky one.</h1>
<% else %>
    <% @questionable_pizza.errors.each do |error| %>
        <%= error %>
    <% end %>
    <h1>Oh boy, something went wrong.</h1>
<% end %>

app/views/questionable_pizzas/create.html.erb
<h1>WOW, that might be the nicest picture I've seen.</h1>
<% if @show_index_link %>
    <%= link_to 'Look at some nice pizza', questionable_pizzas_url %>
<% end %>

app/views/questionable_pizzas/index.html.erb
<h1>Examples of Pizza</h1><br>
<%= link_to 'Ask Cam About A New Pizza', questionable_pizzas_ask_cam_url %><br>
<%= render @questionable_pizzas %>
<%= paginate @questionable_pizzas %>