config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
      :sessions => "users/sessions",
      :confirmations => "users/confirmations",
      :passwords => "users/passwords"}
  root 'questionable_pizzas#index'
  get 'questionable_pizzas/ask_cam'
  post 'questionable_pizzas/create' => 'questionable_pizzas#create'
  get 'questionable_pizzas/create' => 'questionable_pizzas#ask_cam'
  get 'questionable_pizzas/cam_says/:id/:is_it_pizza' => 'questionable_pizzas#cam_says'
  get 'questionable_pizzas' => 'questionable_pizzas#index'
  get 'gayyyyyyyyyy' => 'questionable_pizzas#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IsItPizza</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to('Cams Place', root_path) %>
<br>
<br>

<% if @show_login %>
    <% if @current_user.nil? %>
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
            <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
            <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
            <%= f.text_field :email %>
            <%= f.password_field :password %>
            <%= f.hidden_field :redirect_url, :value => @failed_login_redirect_url %>
            <%= f.submit 'Sign in' %>
            <br>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
            <br>
            <%= link_to "Sign Up", new_user_registration_path %>
            <br>
            <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(:user) %><br />
        <% end %>
    <% else %>
        <%= ["bonjour", "ahoy", "oh i didnt c u there", "oh heyyyyy", "is this THE"].sample + "," %>
        <%= @current_user.first_name %>
        "<%= @current_user.middle_name %>"
        <%= @current_user.last_name %>
        <br>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <% end %>
<% end %>

<%= yield %>

</body>
</html>